### ISSUE TITLE
NEMO: Make it more clear what `target_configure` and `your_configure` are

### ISSUE THREAD

**Issue by martin-g** [Yikun/hpc-arm#11]
It is not clear what `-r 'target_configure' -n 'your_configure'`` are in:
https://github.com/Yikun/hpc-arm/blame/02995b868db8ccadd8666161b23b5510c6a5f6e9/NEMO.md#L286

**Comment by HappyCockroach** [comment]
NEMO official server may have a problem, now there is no way to download the complete source package. I will do the verification when I can get the full source package.

**Comment by qinluyao761** [comment]
NEMO's source code package was faulty, and we decided to abandon this guidance.
