### ISSUE TITLE
FVCOM: The download link gives 404

### ISSUE THREAD

**Issue by martin-g** [Yikun/hpc-arm#14]
http://fvcom.smast.umassd.edu/releases/fvcom-4.3.tar.gz returns error 404.

It might be because I am not logged in.
I've created an account with them but in the confirmation email it says: 
```
Attention please: Our staff will check and verify your account. It will take about 7 business days. Your account will not be valid until that.
 Thank you for registering with FVCOM @ MEDML! 
```

So, I won't be able to test FVCOM for now.

**Comment by qinluyao761** [comment]
The FVCOM source code download path is invalid. This guide does not work properly. Let's skip it.
