### ISSUE TITLE
FVCOM: Cannot get the source code

### ISSUE THREAD

**Issue by martin-g** [Yikun/hpc-arm#15]
FVCOM requires registration to download their source code.
So I am not able to test the steps at https://github.com/Yikun/hpc-arm/blob/main/ROMS.md#compiling-and-installing-roms
I've requested an account with them. Hopefully they will approve it!

**Comment by martin-g** [comment]
My account has been approved but still http://fvcom.smast.umassd.edu/releases/fvcom-4.3.tar.gz returns 404 and I have no access to http://code.fvcom.org/

**Comment by qinluyao761** [comment]
The FVCOM source code download path is invalid. This guide does not work properly. Let's skip it.
