### ISSUE TITLE
GROMACS: Use Arm Performance Libraries (Free ArmPL) ?!

### ISSUE THREAD

**Issue by martin-g** [Yikun/hpc-arm#17]
GROMACS [mentions](https://manual.gromacs.org/documentation/current/install-guide/index.html#using-arm-performance-libraries) usage of ArmPL.
There is a free download of ArmPL [here](https://developer.arm.com/tools-and-software/server-and-hpc/downloads/arm-performance-libraries).

Do you think we should make use of it for GROMACS ?
If YES, then should we use it also for the other projects ?

**Comment by HappyCockroach** [comment]
I think the answer is NO.
The purpose of these documents is to help with basic software migration.
We will have another performance optimization repository later, containing optimization documentation and patches for the kunpeng platform.

**Comment by martin-g** [comment]
Thanks for your answer, @HappyCockroach !
